/**:
    controller_manager:
        ros__parameters:
            update_rate: 1000  # Hz
            use_sim_time: True

            # ARM BROADCASTER
            arm_joint_state_broadcaster:
                type: joint_state_broadcaster/JointStateBroadcaster

            # ARM CONTROLLERS
            joint_trajectory_controller:
                type: joint_trajectory_controller/JointTrajectoryController
            twist_controller:
                type: picknik_twist_controller/PicknikTwistController
            #robotiq_gripper_controller:
            #    type: position_controllers/GripperActionController
            fault_controller:
                type: picknik_reset_fault_controller/PicknikResetFaultController

            # PLATFORM CONTROLLERS
            #joint_state_broadcaster.type: 'joint_state_broadcaster/JointStateBroadcaster'
            velocity_controller.type: 'mecanum_drive_controller/MecanumDriveController'

    joint_trajectory_controller:
        ros__parameters:
            joints:
            - arm/joint_1
            - arm/joint_2
            - arm/joint_3
            - arm/joint_4
            - arm/joint_5
            - arm/joint_6
            - arm/joint_7
            command_interfaces:
            - position
            state_interfaces:
            - position
            - velocity
            state_publish_rate: 100.0
            action_monitor_rate: 20.0
            allow_partial_joints_goal: false
            constraints:
                stopped_velocity_tolerance: 0.0
                goal_time: 0.0

    twist_controller:
        ros__parameters:
            joint: tcp
            interface_names:
            - twist.linear.x
            - twist.linear.y
            - twist.linear.z
            - twist.angular.x
            - twist.angular.y
            - twist.angular.z

    # robotiq_gripper_controller:
    #     ros__parameters:
    #         default: true
    #         joint: robotiq_85_left_knuckle_joint
    #         allow_stalling: true

    velocity_controller:
        ros__parameters:
            use_sim_time: true
            command_joint_names: ["front_left_wheel", "rear_left_wheel", "rear_right_wheel", "front_right_wheel"]
            state_joint_names: ["front_left_wheel", "rear_left_wheel", "rear_right_wheel", "front_right_wheel"]
            interface_name: "velocity"
            use_stamped_vel: false
            base_frame_id: "base_link"
            tf_frame: "rbkk3/"
            tf_topic: "/tf"
            kinematics: 
                wheels_radius: 0.0759
                sum_of_robot_center_projection_on_X_Y_axis: 0.5945
