/rbkk3_0001:
    controller_manager:
        ros__parameters:
            update_rate: 1000  # Hz
            use_sim_time: True

            # ARM BROADCASTER
            rbkk3_0001_arm_joint_state_broadcaster:
                type: joint_state_broadcaster/JointStateBroadcaster

            # ARM CONTROLLERS
            rbkk3_0001_arm_joint_trajectory_controller:
                type: joint_trajectory_controller/JointTrajectoryController
            rbkk3_0001_arm_twist_controller:
                type: picknik_twist_controller/PicknikTwistController
            #robotiq_gripper_controller:
            #    type: position_controllers/GripperActionController
            rbkk3_0001_arm_fault_controller:
                type: picknik_reset_fault_controller/PicknikResetFaultController
            rbkk3_0001_arm_effort_joint_controller:
                type: effort_controllers/JointGroupEffortController
            
            #arm_group_controller:
            #    type: joint_trajectory_controller/JointTrajectoryController

            # PLATFORM CONTROLLERS
            rbkk3_0001_platform_joint_state_broadcaster.type: 'joint_state_broadcaster/JointStateBroadcaster'
            rbkk3_0001_platform_velocity_controller:
                type: 'mecanum_drive_controller/MecanumDriveController'

    rbkk3_0001_arm_joint_state_broadcaster:
        ros__parameters:
            joints:
                - rbkk3_0001/arm/joint_1
                - rbkk3_0001/arm/joint_2
                - rbkk3_0001/arm/joint_3
                - rbkk3_0001/arm/joint_4
                - rbkk3_0001/arm/joint_5
                - rbkk3_0001/arm/joint_6
                - rbkk3_0001/arm/joint_7

    rbkk3_0001_platform_joint_state_broadcaster:
        ros__parameters:
            joints:
                - rbkk3_0001/platform/front_left_wheel
                - rbkk3_0001/platform/front_right_wheel
                - rbkk3_0001/platform/rear_left_wheel
                - rbkk3_0001/platform/rear_right_wheel

    rbkk3_0001_arm_joint_trajectory_controller:
        ros__parameters:
            joints:
            - rbkk3_0001/arm/joint_1
            - rbkk3_0001/arm/joint_2
            - rbkk3_0001/arm/joint_3
            - rbkk3_0001/arm/joint_4
            - rbkk3_0001/arm/joint_5
            - rbkk3_0001/arm/joint_6
            - rbkk3_0001/arm/joint_7
            command_interfaces:
            - effort
            state_interfaces:
            - position
            - velocity
            state_publish_rate: 100.0
            action_monitor_rate: 20.0
            allow_partial_joints_goal: false
            constraints:
                stopped_velocity_tolerance: 0.0
                goal_time: 0.0
            gains:
                rbkk3_0001/arm/joint_1:
                    p: 100.0
                    d: 10.0
                    i: 1.0
                rbkk3_0001/arm/joint_2:
                    p: 100.0
                    d: 10.0
                    i: 1.0
                rbkk3_0001/arm/joint_3:
                    p: 100.0
                    d: 10.0
                    i: 1.0
                rbkk3_0001/arm/joint_4:
                    p: 100.0
                    d: 10.0
                    i: 1.0
                rbkk3_0001/arm/joint_5:
                    p: 100.0
                    d: 10.0
                    i: 1.0
                rbkk3_0001/arm/joint_6:
                    p: 100.0
                    d: 10.0
                    i: 1.0
                rbkk3_0001/arm/joint_7:
                    p: 100.0
                    d: 10.0
                    i: 1.0

    rbkk3_0001_arm_effort_joint_controller:
        ros__parameters:
            joints:
            - rbkk3_0001/arm/joint_1
            - rbkk3_0001/arm/joint_2
            - rbkk3_0001/arm/joint_3
            - rbkk3_0001/arm/joint_4
            - rbkk3_0001/arm/joint_5
            - rbkk3_0001/arm/joint_6
            - rbkk3_0001/arm/joint_7

    rbkk3_0001_arm_twist_controller:
        ros__parameters:
            joint: tcp
            interface_names:
            - twist.linear.x
            - twist.linear.y
            - twist.linear.z
            - twist.angular.x
            - twist.angular.y
            - twist.angular.z

    # robotiq_gripper_controller:
    #     ros__parameters:
    #         default: true
    #         joint: robotiq_85_left_knuckle_joint
    #         allow_stalling: true

    rbkk3_0001_platform_velocity_controller:
        ros__parameters:
            use_sim_time: true
            command_joint_names: ["rbkk3_0001/platform/front_left_wheel", "rbkk3_0001/platform/rear_left_wheel", "rbkk3_0001/platform/rear_right_wheel", "rbkk3_0001/platform/front_right_wheel"]
            state_joint_names: ["rbkk3_0001/platform/front_left_wheel", "rbkk3_0001/platform/rear_left_wheel", "rbkk3_0001/platform/rear_right_wheel", "rbkk3_0001/platform/front_right_wheel"]
            interface_name: "velocity"
            use_stamped_vel: false
            base_frame_id: "rbkk3_0001/platform/base_link"
            odom_frame_id: "rbkk3_0001/odom"
            # tf_frame: "rbkk3_0001/"
            tf_topic: "/tf"
            kinematics:
                wheels_radius: 0.0759
                sum_of_robot_center_projection_on_X_Y_axis: 0.5945


    # This config file is used by ros2_control
    #arm_group_controller:
        #ros__parameters:
            #joints:
            #- arm/joint_1
            #- arm/joint_2
            #- arm/joint_3
            #- arm/joint_4
            #- arm/joint_5
            #- arm/joint_6
            #- arm/joint_7
            #command_interfaces:
            #- position
            #state_interfaces:
            #- position
            #- velocity


# # MoveIt uses this configuration for controller management

    #moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

    #moveit_simple_controller_manager:
        #controller_names:
            #- arm_group_controller

# arm_group_controller:
#     type: FollowJointTrajectory
#     action_ns: follow_joint_trajectory
#     default: true
#     joints:
#     - arm/joint_1
#     - arm/joint_2
#     - arm/joint_3
#     - arm/joint_4
#     - arm/joint_5
#     - arm/joint_6
#     - arm/joint_7
