w200_0000:
  joy_teleop/teleop_twist_joy_node:
    ros__parameters:
      use_sim_time: True
      axis_linear.x: 1
      scale_linear.x: 0.5
      scale_linear_turbo.x: 1.0
      axis_angular.yaw: 0
      scale_angular.yaw: 2.4
      scale_angular_turbo.yaw: 2.4
      enable_button: 4
      enable_turbo_button: 5
  joy_teleop/joy_node:
    ros__parameters:
      use_sim_time: True
      deadzone: 0.1
      autorepeat_rate: 20.0
      dev: '/dev/input/ps4'
